-- Add password column
ALTER TABLE public.users_guru ADD COLUMN IF NOT EXISTS password VARCHAR(100);

-- Add Guru
INSERT INTO public.users_guru (nama, email, role, password)
VALUES ('Admin BK', 'masukbk', 'guru_bk', 'masukbk')
ON CONFLICT (email) DO UPDATE SET password = 'masukbk';

-- Seed Instruments
INSERT INTO public.instruments (id, nama, deskripsi, kategori, total_soal) VALUES
('akpd_7', 'AKPD Kelas 7', 'Angket Kebutuhan Peserta Didik untuk Kelas 7', 'Kebutuhan', 40),
('aum', 'AUM Umum', 'Alat Ungkap Masalah Umum', 'Masalah', 40),
('bullying', 'Asesmen Bullying', 'Deteksi Risiko dan Peran Bullying', 'Sosial', 10),
('self_esteem', 'Self Esteem', 'Tingkat Harga Diri', 'Pribadi', 10),
('motivasi', 'Motivasi Belajar', 'Tingkat Motivasi dan Ketekunan Belajar', 'Belajar', 10),
('multiple_intelligence', 'Kecerdasan Majemuk', 'Pemetaan Bakat dan Kecerdasan Dominan', 'Karier', 16),
('sosiometri', 'Sosiometri', 'Pemetaan Relasi Sosial Kelas', 'Sosial', 0)
ON CONFLICT (id) DO NOTHING;

-- Seed Questions
INSERT INTO public.questions (instrument_id, no_urut, pernyataan, bidang, pilihan_jawaban) VALUES
('akpd_7', 1, 'Aku sering bingung, sebenarnya apa sih kelebihan dan bakatku?', 'Pribadi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 2, 'Kalau lagi marah atau sedih, aku suka susah mengendalikan diri dan gampang emosi.', 'Pribadi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 3, 'Aku sering merasa malu atau nggak pede kalau disuruh maju ke depan kelas.', 'Pribadi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 4, 'Aku pengen tahu cara menjaga kebersihan badanku biar tetap sehat terus.', 'Pribadi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 5, 'Kadang aku ngerasa malas banget buat berangkat sekolah atau ngerjain tugas.', 'Pribadi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 6, 'Aku merasa kurang pandai merawat diri atau mengatur penampilan.', 'Pribadi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 7, 'Aku sering merasa bersalah terus-terusan kalau ngelakuin kesalahan kecil.', 'Pribadi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 8, 'Aku pengen tahu cara ngilangin rasa bosan dan stres waktu sendirian di rumah.', 'Pribadi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 9, 'Aku sering merasa minder karena kondisi badanku (terlalu gemuk, kurus, atau pendek).', 'Pribadi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 10, 'Aku pengen diajarin cara bersyukur dan lebih nerima diriku apa adanya.', 'Pribadi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 11, 'Aku merasa susah atau malu buat ngajak ngobrol teman baru kenal.', 'Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 12, 'Aku sering kepikiran dan cemas kalau lagi musuhan atau beda pendapat sama teman.', 'Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 13, 'Aku susah nolak kalau diajak teman main atau bolos, padahal aku tahu itu salah.', 'Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 14, 'Aku kadang bingung gimana cara ngobrol yang sopan sama guru atau orang yang lebih tua.', 'Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 15, 'Aku sering merasa dijauhi atau nggak diajak main sama teman-teman sekelas.', 'Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 16, 'Aku bingung gimana cara negur atau nasehatin teman tanpa bikin dia emosi.', 'Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 17, 'Aku pengen tahu gimana sih batas pergaulan laki-laki dan perempuan yang bener.', 'Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 18, 'Aku merasa susah membaur sama lingkungan anak-anak tetangga di rumah.', 'Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 19, 'Aku ngerasa gampang banget terpengaruh ikut-ikutan kelakuan jelek teman-teman.', 'Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 20, 'Aku butuh diajarin cara minta maaf yang bener kalau aku punya salah sama orang lain.', 'Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 21, 'Aku bingung gimana cara ngatur waktu antara main, bantu orang tua di rumah, dan belajar.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 22, 'Waktu guru ngejelasin pelajaran di depan, aku sering ngantuk dan susah fokus.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 23, 'Aku belum tahu cara belajar yang paling pas buat aku biar cepat paham dan masuk ke otak.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 24, 'Kalau besok mau ulangan, malamnya aku sering takut, cemas, atau malah nggak bisa tidur.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 25, 'Aku sering lupa ngerjain PR karena keasyikan main bareng teman atau bantu di rumah.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 26, 'Aku butuh diajarin cara nyari bahan tugas atau minjem buku pelajaran yang gratis.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 27, 'Aku sering gugup sampai nge-blank (lupa semua) kalau tiba-tiba disuruh guru maju.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 28, 'Aku pengen tahu cara bikin catetan atau rangkuman yang gampang buat dihafal.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 29, 'Aku sering ngerasa putus asa kalau udah nyoba belajar tapi tetap nggak paham-paham.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 30, 'Aku pengen diajarin cara ngilangin rasa malas belajar yang sering datang tiba-tiba.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 31, 'Aku belum tahu kalau udah besar nanti pengen kerja jadi apa.', 'Karier', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 32, 'Aku pengen tahu macam-macam pekerjaan yang bisa ngasilin uang halal buat bantu keluarga.', 'Karier', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 33, 'Aku bingung mau milih eskul (ekstrakurikuler) apa yang cocok buat bakatku.', 'Karier', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 34, 'Aku butuh info, nanti habis lulus SMP ini sebaiknya lanjut ke SMA, SMK, atau Pesantren ya?', 'Karier', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 35, 'Aku kadang takut cita-citaku nggak bakal kecapai karena keluargaku nggak punya banyak biaya.', 'Karier', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 36, 'Aku pengen banget cari sekolah lanjutan yang ada beasiswanya gratis.', 'Karier', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 37, 'Aku pengen tahu pekerjaan apa yang kira-kira cocok sama hobiku sekarang.', 'Karier', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 38, 'Aku belum ngerti kenapa nilai rapot sekarang itu penting buat daftar sekolah nanti.', 'Karier', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 39, 'Aku belum tahu banyak informasi tentang pilihan jurusan di SMK yang cocok buatku.', 'Karier', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('akpd_7', 40, 'Aku butuh panduan cara ngenalin minat dan potensi diriku buat persiapan masa depan.', 'Karier', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 1, 'Akhir-akhir ini aku gampang capek, pusing, atau kurang sehat waktu jam sekolah.', 'Fisik & Kesehatan', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 2, 'Aku sering nggak sarapan dari rumah, jadi perut kerasa perih atau lemes di kelas.', 'Fisik & Kesehatan', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 3, 'Aku punya sakit bawaan atau gampang drop yang bikin aku sering bolos sekolah.', 'Fisik & Kesehatan', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 4, 'Mata aku sering perih atau kurang jelas kalau lihat tulisan di papan tulis.', 'Fisik & Kesehatan', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 5, 'Aku merasa badanku terlalu kurus, gemuk, atau pendek, dan itu bikin nggak nyaman.', 'Fisik & Kesehatan', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 6, 'Gigiku sering sakit, sariawan, atau badanku gatal-gatal pas lagi belajar di kelas.', 'Fisik & Kesehatan', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 7, 'Aku ngerasa diriku ini banyak kurangnya, jelek, atau nggak sepintar teman-teman.', 'Diri Pribadi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 8, 'Aku sering merasa sangat kesepian walaupun lagi rame kumpul sama orang.', 'Diri Pribadi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 9, 'Aku sering merasa hidup ini berat banget dan kaya nggak punya tujuan yang jelas.', 'Diri Pribadi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 10, 'Aku sering tiba-tiba ngerasa ketakutan atau cemas sendiri tanpa alasan yang jelas.', 'Diri Pribadi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 11, 'Di rumah aku sering dimarahi, disalahkan, atau kurang diperhatiin sama bapak/ibu.', 'Keluarga', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 12, 'Orang tuaku sering berantem atau ribut di rumah dan itu bikin aku sedih banget.', 'Keluarga', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 13, 'Aku sering kepikiran masalah keluarga sampai nangis sendiri di kamar.', 'Keluarga', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 14, 'Orang tuaku terlalu sibuk kerja atau ngurus hal lain sampai jarang ngobrol sama aku.', 'Keluarga', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 15, 'Aku ngerasa dibeda-bedain, dibanding-bandingin, atau pilih kasih sama saudara di rumah.', 'Keluarga', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 16, 'Aku sering digangguin, diejek, atau dimintain uang paksa sama teman di sekolah.', 'Hubungan Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 17, 'Aku ngerasa kesepian, nggak punya teman akrab yang bisa diajak curhat bareng.', 'Hubungan Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 18, 'Aku lagi berantem atau musuhan lama sama teman sekelas dan belum baikan.', 'Hubungan Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 19, 'Aku merasa canggung, takut, atau segan kalau harus ngomong sama guru.', 'Hubungan Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 20, 'Aku merasa dijauhi gara-gara kondisi rumah, seragam, atau penampilanku.', 'Hubungan Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 21, 'Aku merasa susah bergaul karena bahasaku atau caraku ngomong beda sama mereka.', 'Hubungan Sosial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 22, 'Aku kadang sedih karena nggak punya uang jajan atau nggak bisa jajan kayak teman lain.', 'Ekonomi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 23, 'Keluargaku lagi kesusahan uang buat bayar tunggakan atau daftar ulang sekolahku.', 'Ekonomi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 24, 'Aku harus ikut kerja kasar buat bantu orang tua cari uang, jadi capek kalau di kelas.', 'Ekonomi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 25, 'Seragam, tas, atau sepatuku udah rusak tapi bapak/ibu belum ada uang buat beli baru.', 'Ekonomi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 26, 'Orang tuaku lagi banyak tanggungan atau hutang yang bikin suasana rumah jadi muram.', 'Ekonomi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 27, 'Aku sering nahan lapar di sekolah karena nggak dibekali uang saku atau makanan sama sekali.', 'Ekonomi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 28, 'Aku khawatir orang tuaku kesulitan buat beli beras atau makanan buat keluarga di rumah.', 'Ekonomi', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 29, 'Aku sering takut dan kepikiran, nanti masa depanku bakal suram nggak ya?', 'Masa Depan', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 30, 'Aku khawatir banget nggak bisa lanjut sekolah gara-gara nggak ada biayanya.', 'Masa Depan', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 31, 'Orang tuaku nyuruh aku cepat-cepat kerja aja habis lulus sekolah ini.', 'Masa Depan', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 32, 'Aku bingung karena apa yang aku pengen buat masa depan ditolak sama orang tua.', 'Masa Depan', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 33, 'Aku merasa nggak punya kepintaran apa-apa yang bisa kepakai buat cari kerja nanti.', 'Masa Depan', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 34, 'Aku sering dengar kalau cari kerja sekarang susah banget, jadi aku takut nanti nganggur.', 'Masa Depan', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 35, 'Aku ngerasa pelajaran di sekolah ini susah-susah banget, aku sering nggak nyambung.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 36, 'Aku nggak punya buku cetak, LKS, atau tempat terang buat belajar di rumah.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 37, 'Aku sering malas banget ngerjain PR dan milih mabar game atau main HP.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 38, 'Cara guru ngejelasin kadang kecepatan atau galak, aku jadi takut nanya.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 39, 'Jarak rumah ke sekolah lumayan jauh atau susah angkutannya, bikin sering kesiangan.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('aum', 40, 'Nilai-nilaiku banyak yang jelek, dan aku takut banget kalau sampai nggak naik kelas.', 'Belajar', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('bullying', 1, 'Pernah nggak kamu dipanggil pakai nama bapakmu atau ejekan fisik yang bikin kamu sakit hati?', 'Verbal', '[{"label":"Sering","value":3},{"label":"Pernah","value":2},{"label":"Tidak Pernah","value":1}]'),
('bullying', 2, 'Pernah nggak kamu diolok-olok, disorakin, atau diketawain sekelas pas lagi ngomong?', 'Verbal', '[{"label":"Sering","value":3},{"label":"Pernah","value":2},{"label":"Tidak Pernah","value":1}]'),
('bullying', 3, 'Pernah nggak kamu dipukul, didorong, atau dijegal sampai jatuh sama teman dengan sengaja?', 'Fisik', '[{"label":"Sering","value":3},{"label":"Pernah","value":2},{"label":"Tidak Pernah","value":1}]'),
('bullying', 4, 'Pernah nggak kamu ditendang, dicubit, atau dilempar pakai barang sama teman?', 'Fisik', '[{"label":"Sering","value":3},{"label":"Pernah","value":2},{"label":"Tidak Pernah","value":1}]'),
('bullying', 5, 'Pernah nggak barang-barangmu (sepatu, buku, uang) disembunyiin, dirusak, atau dimintain paksa?', 'Fisik', '[{"label":"Sering","value":3},{"label":"Pernah","value":2},{"label":"Tidak Pernah","value":1}]'),
('bullying', 6, 'Pernah nggak kamu sengaja ditinggalin dan dilarang ikut main sama anak-anak lain?', 'Sosial', '[{"label":"Sering","value":3},{"label":"Pernah","value":2},{"label":"Tidak Pernah","value":1}]'),
('bullying', 7, 'Pernah nggak teman-teman tiba-tiba diam, bisik-bisik, atau bubar waktu kamu mau ikut ngumpul?', 'Sosial', '[{"label":"Sering","value":3},{"label":"Pernah","value":2},{"label":"Tidak Pernah","value":1}]'),
('bullying', 8, 'Pernah nggak ada teman yang nyebarin gosip, fitnah, atau cerita bohong tentang kamu?', 'Sosial', '[{"label":"Sering","value":3},{"label":"Pernah","value":2},{"label":"Tidak Pernah","value":1}]'),
('bullying', 9, 'Pernah nggak kamu dikirimin chat ancaman, dimaki, atau ditag dengan kata kasar di grup WA/FB?', 'Cyber', '[{"label":"Sering","value":3},{"label":"Pernah","value":2},{"label":"Tidak Pernah","value":1}]'),
('bullying', 10, 'Pernah nggak fotomu atau aibmu diam-diam disebar buat bahan ketawaan di status sosmed?', 'Cyber', '[{"label":"Sering","value":3},{"label":"Pernah","value":2},{"label":"Tidak Pernah","value":1}]'),
('self_esteem', 1, 'Aku merasa bersyukur dan bangga jadi diriku sendiri apa adanya.', 'Penghargaan Diri', '[{"label":"Sangat Setuju","value":4},{"label":"Setuju","value":3},{"label":"Kurang Setuju","value":2},{"label":"Tidak Setuju","value":1}]'),
('self_esteem', 2, 'Kadang aku mikir kalau aku ini anak yang nggak berguna dan nyusahin keluarga.', 'Penerimaan Diri', '[{"label":"Sangat Setuju","value":1},{"label":"Setuju","value":2},{"label":"Kurang Setuju","value":3},{"label":"Tidak Setuju","value":4}]'),
('self_esteem', 3, 'Aku yakin suatu saat nanti aku bisa jadi orang sukses yang merubah nasib keluargaku.', 'Penghargaan Diri', '[{"label":"Sangat Setuju","value":4},{"label":"Setuju","value":3},{"label":"Kurang Setuju","value":2},{"label":"Tidak Setuju","value":1}]'),
('self_esteem', 4, 'Kalau ada tugas maju atau disuruh guru, aku sering ngerasa pasti salah duluan.', 'Percaya Diri', '[{"label":"Sangat Setuju","value":1},{"label":"Setuju","value":2},{"label":"Kurang Setuju","value":3},{"label":"Tidak Setuju","value":4}]'),
('self_esteem', 5, 'Aku berani nanya atau minta diajarin ulang ke guru kalau pelajarannya belum nyambung.', 'Percaya Diri', '[{"label":"Sangat Setuju","value":4},{"label":"Setuju","value":3},{"label":"Kurang Setuju","value":2},{"label":"Tidak Setuju","value":1}]'),
('self_esteem', 6, 'Aku sering merasa malu sama orang kalau nginget kondisi ekonomi atau rumah orang tuaku.', 'Penerimaan Diri', '[{"label":"Sangat Setuju","value":1},{"label":"Setuju","value":2},{"label":"Kurang Setuju","value":3},{"label":"Tidak Setuju","value":4}]'),
('self_esteem', 7, 'Aku merasa punya sifat dan kelakuan yang baik, dan teman-teman juga suka itu.', 'Penghargaan Diri', '[{"label":"Sangat Setuju","value":4},{"label":"Setuju","value":3},{"label":"Kurang Setuju","value":2},{"label":"Tidak Setuju","value":1}]'),
('self_esteem', 8, 'Aku sering iri dan berandai-andai pengen banget dilahirin jadi orang lain aja.', 'Penerimaan Diri', '[{"label":"Sangat Setuju","value":1},{"label":"Setuju","value":2},{"label":"Kurang Setuju","value":3},{"label":"Tidak Setuju","value":4}]'),
('self_esteem', 9, 'Walaupun susah, aku selalu nyoba nyelesain masalahku sendiri dulu tanpa nyerah.', 'Percaya Diri', '[{"label":"Sangat Setuju","value":4},{"label":"Setuju","value":3},{"label":"Kurang Setuju","value":2},{"label":"Tidak Setuju","value":1}]'),
('self_esteem', 10, 'Setiap kali ngaca atau lihat fotoku, aku ngerasa banyak banget jeleknya.', 'Penerimaan Diri', '[{"label":"Sangat Setuju","value":1},{"label":"Setuju","value":2},{"label":"Kurang Setuju","value":3},{"label":"Tidak Setuju","value":4}]'),
('motivasi', 1, 'Aku belajar sungguh-sungguh karena aku memang suka dan ingin tahu lebih banyak.', 'Intrinsik', '[{"label":"Selalu","value":4},{"label":"Sering","value":3},{"label":"Kadang-kadang","value":2},{"label":"Tidak Pernah","value":1}]'),
('motivasi', 2, 'Aku merasa puas dan senang kalau berhasil memecahkan soal pelajaran yang susah.', 'Intrinsik', '[{"label":"Selalu","value":4},{"label":"Sering","value":3},{"label":"Kadang-kadang","value":2},{"label":"Tidak Pernah","value":1}]'),
('motivasi', 3, 'Aku rajin belajar karena takut dimarahi guru atau dihukum orang tua.', 'Ekstrinsik', '[{"label":"Selalu","value":4},{"label":"Sering","value":3},{"label":"Kadang-kadang","value":2},{"label":"Tidak Pernah","value":1}]'),
('motivasi', 4, 'Aku semangat ngerjain tugas kalau dijanjiin hadiah atau uang jajan tambahan.', 'Ekstrinsik', '[{"label":"Selalu","value":4},{"label":"Sering","value":3},{"label":"Kadang-kadang","value":2},{"label":"Tidak Pernah","value":1}]'),
('motivasi', 5, 'Kalau dikasih PR yang banyak, aku tetap berusaha nyelesain sampai tuntas.', 'Ketekunan', '[{"label":"Selalu","value":4},{"label":"Sering","value":3},{"label":"Kadang-kadang","value":2},{"label":"Tidak Pernah","value":1}]'),
('motivasi', 6, 'Aku gampang menyerah dan langsung nutup buku kalau nemu pelajaran yang susah.', 'Ketekunan', '[{"label":"Selalu","value":1},{"label":"Sering","value":2},{"label":"Kadang-kadang","value":3},{"label":"Tidak Pernah","value":4}]'),
('motivasi', 7, 'Walaupun nggak ada ulangan besok, aku tetap meluangkan waktu buat belajar di rumah.', 'Ketekunan', '[{"label":"Selalu","value":4},{"label":"Sering","value":3},{"label":"Kadang-kadang","value":2},{"label":"Tidak Pernah","value":1}]'),
('motivasi', 8, 'Mencari nilai bagus adalah kepuasan pribadiku, bukan cuma buat pamer ke teman.', 'Intrinsik', '[{"label":"Selalu","value":4},{"label":"Sering","value":3},{"label":"Kadang-kadang","value":2},{"label":"Tidak Pernah","value":1}]'),
('motivasi', 9, 'Aku cuma mau mencatat pelajaran kalau disuruh atau diawasin guru.', 'Ekstrinsik', '[{"label":"Selalu","value":4},{"label":"Sering","value":3},{"label":"Kadang-kadang","value":2},{"label":"Tidak Pernah","value":1}]'),
('motivasi', 10, 'Belajar hal baru bikin aku ngerasa berkembang dan makin pintar setiap hari.', 'Intrinsik', '[{"label":"Selalu","value":4},{"label":"Sering","value":3},{"label":"Kadang-kadang","value":2},{"label":"Tidak Pernah","value":1}]'),
('multiple_intelligence', 1, 'Aku suka banget nulis cerita, puisi, atau ngisi diary kegiatan sehari-hari.', 'Linguistik', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 2, 'Aku gampang ngafal kata-kata baru, jago berdebat, atau suka ngobrol lama.', 'Linguistik', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 3, 'Pelajaran berhitung kayak matematika atau main tebak-tebakan logika itu seru banget buatku.', 'Logika-Matematik', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 4, 'Aku suka nyari tahu kenapa suatu barang bisa rusak atau gimana mesin bekerja.', 'Logika-Matematik', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 5, 'Aku suka nge-gambar, corat-coret, atau ngebayangin bentuk bangunan di kepalaku.', 'Visual-Spasial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 6, 'Aku gampang ingat jalan dan jarang tersesat kalau pergi ke tempat baru.', 'Visual-Spasial', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 7, 'Aku nggak bisa diam lama-lama, tanganku gatal pengen gerak atau praktek langsung.', 'Kinestetik', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 8, 'Aku jago olahraga, nari, atau mainin barang dengan tangkas tanpa gampang jatuh.', 'Kinestetik', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 9, 'Aku suka banget nyanyi, dengerin musik, atau hafal nada lagu dengan cepat.', 'Musikal', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 10, 'Kalau lagi belajar atau ngerjain tugas, aku lebih fokus kalau sambil dengerin lagu.', 'Musikal', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 11, 'Aku punya banyak teman dan gampang banget berbaur di lingkungan baru.', 'Interpersonal', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 12, 'Teman-teman sering curhat ke aku karena aku bisa ngertiin perasaan mereka.', 'Interpersonal', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 13, 'Aku lebih suka kerja sendirian dan butuh waktu tenang buat mikirin diriku sendiri.', 'Intrapersonal', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 14, 'Aku tahu pasti apa kelebihan dan kelemahanku, serta tujuan hidupku ke depan.', 'Intrapersonal', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 15, 'Aku suka banget melihara hewan, merawat tanaman, atau jalan-jalan ke alam bebas.', 'Naturalis', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]'),
('multiple_intelligence', 16, 'Aku peduli banget sama lingkungan, misalnya nggak tega buang sampah sembarangan.', 'Naturalis', '[{"label":"Ya","value":1},{"label":"Tidak","value":0}]');
