export const AKPD_INTERPRETATION_BANK: Record<number, string> = {
  1: "Kebingungan dalam mengenali kelebihan dan bakat diri.",
  2: "Kesulitan dalam mengendalikan diri dan emosi saat marah atau sedih.",
  3: "Sering merasa malu atau kurang percaya diri untuk tampil di depan kelas.",
  4: "Kurangnya pemahaman cara menjaga kebersihan dan kesehatan badan.",
  5: "Sering merasa malas untuk berangkat sekolah atau mengerjakan tugas.",
  6: "Kurangnya keterampilan dalam merawat diri atau mengatur penampilan.",
  7: "Kecenderungan merasa bersalah berlebihan atas kesalahan kecil.",
  8: "Kebingungan mencari cara menghilangkan rasa bosan dan stres di rumah.",
  9: "Merasa minder terkait kondisi fisik tubuh (terlalu gemuk, kurus, atau pendek).",
  10: "Kesulitan untuk bersyukur dan menerima keadaan diri apa adanya.",
  11: "Merasa canggung atau malu saat mengajak mengobrol teman yang baru dikenal.",
  12: "Mudah cemas dan terus memikirkan perselisihan dengan teman.",
  13: "Kesulitan menolak ajakan teman untuk melakukan hal yang salah (bolos/main).",
  14: "Kebingungan tata krama berkomunikasi dengan guru atau orang yang lebih tua.",
  15: "Merasa dijauhi atau tidak diajak bermain oleh teman sekelas.",
  16: "Kebingungan cara menegur teman tanpa memicu pertengkaran atau emosi.",
  17: "Kurangnya pemahaman tentang batasan pergaulan laki-laki dan perempuan.",
  18: "Kesulitan membaur dengan lingkungan anak-anak di sekitar rumah.",
  19: "Sangat mudah terpengaruh oleh perilaku buruk teman-teman sebaya.",
  20: "Kurangnya keterampilan dalam meminta maaf yang baik atas kesalahan.",
  21: "Kesulitan mengatur waktu antara bermain, membantu orang tua, dan belajar.",
  22: "Sering merasa ngantuk dan sulit fokus saat guru menjelaskan pelajaran.",
  23: "Belum menemukan metode belajar yang pas dan efektif untuk diri sendiri.",
  24: "Mengalami kecemasan berlebihan atau kesulitan tidur menjelang hari ulangan.",
  25: "Sering lupa mengerjakan tugas karena asyik bermain atau membantu di rumah.",
  26: "Kebingungan mencari bahan tugas pelajaran atau meminjam buku secara gratis.",
  27: "Sering merasa sangat gugup hingga kehilangan konsentrasi saat disuruh maju.",
  28: "Belum mengetahui cara membuat ringkasan pelajaran yang mudah dihafal.",
  29: "Sering merasa putus asa ketika gagal memahami pelajaran meski sudah mencoba.",
  30: "Kesulitan mengatasi rasa malas belajar yang sering datang tiba-tiba.",
  31: "Kebingungan menentukan cita-cita atau pekerjaan di masa depan.",
  32: "Kurangnya informasi mengenai jenis pekerjaan untuk membantu keluarga.",
  33: "Kebingungan memilih kegiatan ekstrakurikuler yang sesuai dengan bakat.",
  34: "Kurangnya informasi pilihan sekolah lanjutan setelah lulus SMP (SMA/SMK).",
  35: "Merasa takut cita-cita tidak tercapai akibat keterbatasan biaya keluarga.",
  36: "Membutuhkan informasi mengenai sekolah lanjutan yang menyediakan beasiswa.",
  37: "Kebingungan mengaitkan hobi saat ini dengan prospek pekerjaan yang cocok.",
  38: "Belum memahami pentingnya nilai rapor untuk mendaftar sekolah lanjutan.",
  39: "Kurangnya informasi mengenai pilihan jurusan di SMK dan kesesuaiannya.",
  40: "Membutuhkan panduan pengenalan minat dan potensi untuk persiapan masa depan."
};
